=== KilianVR/2324_LMSGI_KilianVazquez/UT5/TE/Boletin 5.3/TE54_3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Itinerary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Trip" type="tipoTrip" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tipoTrip">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="Destination" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="DepartureDate" type="xs:date" minOccurs="1" maxOccurs="1" />
            <xs:element name="ArrivalDate" type="xs:date" minOccurs="0" maxOccurs="1" />
            <xs:element name="Price" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
            <xs:element name="Activities" type="tipoActivities" minOccurs="1" maxOccurs="1" />
            <xs:element name="Excursions" type="tipoExcursions" minOccurs="1" maxOccurs="1" />
            <xs:element name="Passengers" type="tipoPassenger" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="code" type="xs:positiveInteger" use="required" />
    </xs:complexType>

    <xs:complexType name="tipoActivities">
        <xs:sequence>
            <xs:element name="Activity" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1" />
                        <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1" />
                        <xs:element name="Date" type="xs:date" minOccurs="1" maxOccurs="1" />
                        <xs:element name="Price" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
                        <xs:element name="Type" minOccurs="0" maxOccurs="1">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Aventura" />
                                    <xs:enumeration value="Cultural" />
                                    <xs:enumeration value="Gastronómica" />
                                    <xs:enumeration value="Deportiva" />
                                    <xs:enumeration value="Otro" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="Seats" type="xs:positiveInteger" minOccurs="1" maxOccurs="1" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoExcursions">
        <xs:sequence>
            <xs:element name="Excursion" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1" />
                        <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1" />
                        <xs:element name="Date" type="xs:date" minOccurs="1" maxOccurs="1" />
                        <xs:element name="Price" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
                        <xs:element name="Destination" type="xs:string" minOccurs="0" maxOccurs="1" />
                        <xs:element name="Seats" type="xs:positiveInteger" minOccurs="1" maxOccurs="1" />
                    </xs:sequence>
                    <xs:attribute name="Type" use="optional" >
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Aventura" />
                                <xs:enumeration value="Cultural" />
                                <xs:enumeration value="Gastronómica" />
                                <xs:enumeration value="Relax" />
                                <xs:enumeration value="Deportiva" />
                                <xs:enumeration value="Otro" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoPassenger">
        <xs:sequence>
            <xs:element name="Passenger" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1" />
                        <xs:element name="LastName" type="xs:string" minOccurs="0" maxOccurs="1" />
                        <xs:element name="BirthDate" type="xs:date" minOccurs="0" maxOccurs="1" />
                        <xs:element name="PassportNumber" type="xs:string" minOccurs="0" maxOccurs="1" />
                        <xs:element name="PhoneNumber" minOccurs="0" maxOccurs="1" >
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="CountryCode" type="xs:positiveInteger" />
                                    <xs:element name="Number" type="xs:positiveInteger" />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="Email" minOccurs="0" maxOccurs="2" >
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="type" use="optional">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="main" />
                                                    <xs:enumeration value="secondary" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                        
                        <xs:element name="RoomNumber" type="xs:string" minOccurs="0" maxOccurs="1" />
                        <xs:element name="RoomType" minOccurs="0" maxOccurs="1">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Individual" />
                                    <xs:enumeration value="Doble" />
                                    <xs:enumeration value="Triple" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="TicketNumber" type="xs:string" minOccurs="1" maxOccurs="1" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>


<!-- Para los atributos
<xsd:attribute name="tipo">
  <xsd:simpleType>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="novela"/>
      <xsd:enumeration value="ensayo"/>
      <xsd:enumeration value="poesia"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:attribute> -->

=== KilianVR/2324_LMSGI_KilianVazquez/UT5/TE/Boletin 5.3/LMSGI_5.3.3.xml
<!-- Ejercicio 3. Itinerario de viaje
Diseña un XML Schema que represente un itinerario de un cruzero.
Cada viaje debería tener los siguientes detalles:

Un viaje tiene un código (atributo, string, requerido y único)

Un viaje tiene un nombre (string, requerido)

Un viaje tiene un destino (string, requerido)

Un viaje tiene una fecha de salida (string, requerido)

Un viaje tiene una fecha de llegada (string, opcional)

Un viaje tiene un precio (numérico, opcional)

Un viaje tiene una lista de actividades (obligratorio)

Cada actividad tiene un nombre (string, requerido)
Cada actividad tiene una descripción (string, opcional)
Cada acttividad tiene una fecha (date, obligatorio)
Cada actividad tiene un precio (numérico, opcional)
Cada actividad tiene un tipo (enumeración: "Aventura", "Cultural", "Gastronómica", "Relax",
"Deportiva", "Otro", opcional)
Cada actividad tiene un número de plazas (entero, obligatorio)

Cada viaje tiene una lista de excursiones (entero, obligatorio)

Tiene un nombre (string, requerido)
Tiene una descripción (string, opcional)
Tiene una fecha (date, obligatorio)
Tiene un precio (numérico, opcional)
Tiene una destino (string, obligatorio), el destino tiene un atributo tipo (enumeración:
"Aventura", "Cultural", "Gastronómica", "Relax", "Deportiva", "Otro", opcional)
Tiene un número de plazas (entero, obligatorio)
Cada viaje tiene una lista de pasajeros (entero, opcional)

Tiene un nombre (string, requerido)
Tiene un apellido (string, opcional)
Tiene una fecha de nacimiento (date, opcional)
Tiene un número de pasaporte (string, opcional)
Tiene un número de teléfono (opcional)
Tiene un email (string, opcional), con un atributo tipo (enumeración: "main", "secondary",
opcional)
Tiene un número de habitación (string, opcional)
Tiene un tipo de habitación (enumeración: "Individual", "Doble", "Triple", opcional)
Número del billete (string, obligatorio)
El XML a validar es el siguiente:

Genera un XML que valide el siguiente XML Schema: -->

<Itinerary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="TE54_3.xsd">

<Trip code="1234">
    <Name>Crucero por el Mediterráneo</Name>
    <Destination>Italia</Destination>
    <DepartureDate>2020-07-01</DepartureDate>
    <ArrivalDate>2020-07-15</ArrivalDate>
    <Price>1500</Price>
    <Activities>
        <Activity>
            <Name>Visita a la Torre de Pisa</Name>
            <Description>Visita a la Torre de Pisa</Description>
            <Date>2020-07-02</Date>
            <Price>20</Price>
            <Type>Cultural</Type>
            <Seats>50</Seats>
        </Activity>
        <Activity>
            <Name>Visita a la Torre de Pisa</Name>
            <Description>Visita a la Torre de Pisa</Description>
            <Date>2020-07-02</Date>
            <Price>20</Price>
            <Type>Cultural</Type>
            <Seats>50</Seats>
        </Activity>
    </Activities>
    <Excursions>
        <Excursion>
            <Name>Visita a la Torre de Pisa</Name>
            <Description>Visita a la Torre de Pisa</Description>
            <Date>2020-07-02</Date>
            <Price>20</Price>
            <Destination>Italia</Destination>
            <Seats>50</Seats>
        </Excursion>
        <Excursion>
            <Name>Visita a Roma</Name>
            <Description>Visita a Roma</Description>
            <Date>2020-07-03</Date>
            <Price>20</Price>
            <Destination>Italia</Destination>
            <Seats>50</Seats>
        </Excursion>
    </Excursions>
    <Passengers>
        <Passenger>
            <Name>John</Name>
            <LastName>Doe</LastName>
            <BirthDate>1990-01-01</BirthDate>
            <PassportNumber>123456789</PassportNumber>
            <PhoneNumber>
                <CountryCode>34</CountryCode>
                <Number>123456789</Number>
            </PhoneNumber>
            <Email type="main">javier@gmail.com</Email>
            <RoomNumber>123</RoomNumber>
            <RoomType>Individual</RoomType>
            <TicketNumber>123456789</TicketNumber>
        </Passenger>
        <Passenger>
            <Name>Jane</Name>
            <LastName>Doe</LastName>
            <BirthDate>1990-01-01</BirthDate>
            <PassportNumber>123456789</PassportNumber>
            <PhoneNumber>
                <CountryCode>34</CountryCode>
                <Number>123456789</Number>
            </PhoneNumber>
            <Email type="main">manuel@gmail.com</Email>
            <Email type="secondary">manuel.office@gmail.com</Email>
            <RoomNumber>123</RoomNumber>
            <RoomType>Individual</RoomType>
            <TicketNumber>123456789</TicketNumber>
        </Passenger>
    </Passengers>
</Trip>
</Itinerary>
